services:
  dev:
    # docker compose run --rm dev /bin/bash
    image: ${REGISTRY}/fx-utils:dev
    build:
      context: . 
      args:
        apt_cacher: ${APT_CACHER}
      dockerfile: Dockerfile.dev
    environment:
      - DISCORD_WEBHOOK_URL
      - GRID_CENTER_ADJUSTMENT=1
      - GRID_RANGE=1
      - GRID_CENTER_MAX=160
    tty: true
    volumes:
      - ./app:/app:delegated
