services:
  dev:
    # docker compose run --rm dev /bin/bash
    image: ${REGISTRY}/fx-utils:dev
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    environment:
      DISCORD_WEBHOOK_URL:
      PAIRS: USDJPY,GBPUSD
      USDJPY_ACCOUNTS: exness:0.07,ic_markets:0.03:false
      USDJPY_GRID_CENTER_ADJUSTMENT: 1
      USDJPY_GRID_RANGE: 1
      USDJPY_GRID_CENTER_MAX: 160
      USDJPY_GRID_CENTER_MIN: 152
      GBPUSD_ACCOUNTS: exness:0.03
      GBPUSD_MAGIC_NUMBER: 8003
      GBPUSD_GRID_STEP_PIPS: 5
      GBPUSD_GRID_CENTER_ADJUSTMENT: 0
      GBPUSD_GRID_RANGE: 1
      GBPUSD_GRID_CENTER_MAX: 1.336
    tty: true
    volumes:
      - "./app:/app"
      - "./data:/data"
